# Site settings
title: Conan Is Blogging
email: conan@conan.is
description: > # this means to ignore newlines until "baseurl:"
  A full-stack dev's experiences in tech
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conan.is" # the base hostname & protocol for your site
twitter_username: conanistweeting
github_username: conan
cv_url: http://conan.is/cv/
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge	
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
