# Site settings
title: Conan Is Blogging
email: ***REMOVED***
meta-description: > # 
  Technology blog about Clojure and things, by Conan Cook
description: > # this means to ignore newlines until "baseurl:"
  (let [s "have"] (some-> 'fn))
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conan.is" # the base hostname & protocol for your site
twitter_username: ***REMOVED***
github_username: conan
cv_url: http://conan.is/cv/
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: pygments	
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
