# Site settings
title: Conan Is Blogging
email: ***REMOVED***
meta-description: > # 
  Technology blog about Clojure and things, by Conan Cook
description: > # this means to ignore newlines until "baseurl:"
  (let [s "have"] (some-> 'fn))
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://conan.is" # the base hostname & protocol for your site
twitter_username: ***REMOVED***
github_username: conan
linkedin_username: conancook
cv_url: http://conan.is/cv/
plugins:
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
